In [24]:
import pandas as pd
import json

df = pd.read_csv("~/Documents/immo_eliza_regression/cleaned_data.csv")
df = df[['id', 'type of property', 'Sub-type', 'City', 'Province', 'Region', 'post code', 'Price', 'Median price PC', 'Garden', 'Terrace','Living area','Bedrooms','Surface of the plot','Garden surface','Swimming pool','Open fire','Terrace surface','Number of frontages','Building condition', 'Kitchen type']]
df.head(10)

,id,type of property,Sub-type,City,Province,Region,post code,Price,Median price PC,Garden,...,Living area,Bedrooms,Surface of the plot,Garden surface,Swimming pool,Open fire,Terrace surface,Number of frontages,Building condition,Kitchen type
0,10092563,APARTMENT,apartment,Antwerpen,Antwerp,Flanders,2000,485000.0,469000.0,0,...,95.0,2.0,0.0,0.0,0,0.0,15.0,3.0,3,3
1,10092564,APARTMENT,duplex,Antwerpen,Antwerp,Flanders,2000,455000.0,469000.0,0,...,100.0,2.0,0.0,0.0,0,0.0,12.0,2.0,3,3
2,10092568,HOUSE,house,Vitrival,Namur,Wallonia,5070,155000.0,220000.0,0,...,80.0,3.0,90.0,0.0,0,0.0,70.0,2.0,1,1
3,10092576,APARTMENT,apartment,Liedekerke,Flemish Brabant,Flanders,1770,195000.0,325999.0,0,...,90.0,2.0,0.0,0.0,0,0.0,8.0,2.0,2,1
4,10092579,APARTMENT,duplex,Wilrijk,Antwerp,Flanders,2610,395000.0,265000.0,0,...,126.0,3.0,0.0,0.0,0,0.0,22.0,2.0,3,3
5,10092590,APARTMENT,apartment,Jette,Flemish Brabant,Brussels,1090,195000.0,281000.0,0,...,73.0,1.0,0.0,0.0,0,0.0,15.0,2.0,3,2
6,10092591,APARTMENT,penthouse,Sint-Lambrechts-Woluwe,Flemish Brabant,Brussels,1200,290000.0,410000.0,0,...,70.0,2.0,0.0,0.0,0,0.0,5.0,3.0,2,3
7,10092602,APARTMENT,duplex,Aalst,East Flanders,Flanders,9300,269250.0,320000.0,0,...,107.0,2.0,0.0,0.0,0,0.0,11.0,2.0,2,3
8,10092603,APARTMENT,penthouse,Aalst,East Flanders,Flanders,9300,378000.0,320000.0,0,...,164.0,3.0,0.0,0.0,0,0.0,33.0,2.0,2,3
9,10092605,APARTMENT,apartment,Heldergem,East Flanders,Flanders,9450,165000.0,323000.0,0,...,88.0,1.0,0.0,0.0,0,0.0,5.0,2.0,1,2

In [22]:
prop_type_list = ['APARTMENT','HOUSE','OTHERS']
corr_dict = {}

for i in prop_type_list:
    corr = df[df['type of property'] == i].corr()
    corr_list = dict(corr['Price'])
    corr_dict[i] = corr_list

with open("correlations.json", "w") as outfile:
    json.dump(corr_dict, outfile, indent=4)

/tmp/ipykernel_75767/871891130.py:5: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr = df[df['type of property'] == i].corr()

In [19]:
national_median = df['Price'].median()

pc_coefs = dict(zip(df['post code'], df['Median price PC']/national_median))

with open("pc_coefs.json", "w") as outfile:
    json.dump(pc_coefs, outfile, indent=4)

In [23]:
num_col_list = ['Living area','Bedrooms','Surface of the plot','Garden surface','Terrace surface','Number of frontages','Building condition', 'Kitchen type']
prop_type_list = ['APARTMENT','HOUSE','OTHERS']
median_dict = {}

for i in prop_type_list:
    dict1 = {}
    for j in num_col_list:
        prop_type_mean = df[(df['type of property']== i) & (df[j] != 0) ][j].median()
        # df.loc[(df['type of property'] == i ), j] = df[j]/prop_type_mean
        dict1[j] = prop_type_mean
    median_dict[i] = dict1

with open("medians.json", "w") as outfile:
    json.dump(median_dict, outfile, indent=4)